/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d671326e-041d-4b0e-bdb2-51e42e6b547f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dlYAmFOD0",
    "aws_user_pools_web_client_id": "26inr7maukef72uvt45e3e2jd7",
    "oauth": {}
};


export default awsmobile;
